[package]
name = "goscript-vm"
version = "0.1.0"
authors = ["oxfeeefeee <pb01005051@gmail.com>"]
edition = "2021"

[dependencies]
slotmap = "1.0"
ordered-float = "3.0"
async-channel = "1.6.1"
async-executor = "1.4.1"
futures-lite = "1.12.0"

[dependencies.goscript-parser]
path = "../parser"
version = "0.1.0"

[dev-dependencies]
time-test = "0.2.2"