[package]
name = "goscript-engine"
version = "0.1.0"
authors = ["oxfeeefeee <pb01005051@gmail.com>"]
edition = "2021"

[features] 
default = ["run_fs"]
run_fs = []
run_zip = ["dep:zip"]   
  
[dependencies]  
slotmap = "1.0"  
futures-lite = "1.12.0"
zip = { version = "0.6.2", features = ["deflate"], default-features = false, optional = true }

[dependencies.goscript-parser] 
path = "../parser"
version = "0.1.0" 

[dependencies.goscript-vm] 
path = "../vm"
version = "0.1.0"

[dependencies.goscript-types] 
path = "../types"
version = "0.1.0"

[dependencies.goscript-codegen]
path = "../codegen"
version = "0.1.0"
   
[dependencies.goscript-pmacro]
path = "../pmacro"
version = "0.1.0"

[dev-dependencies]
time-test = "0.2.2"
criterion = "0.3"

[[bench]]
name = "leet5_benchmark"
harness = false

